# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  IMAGE_TAG: latest

pool:
  vmImage: ubuntu-latest

steps:
- task: Docker@2
  displayName: Build an image
  inputs:
    command: build
    dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
    repository: $(AWS_ACCOUNT_ID).dkr.ecr.$(AWS_REGION).amazonaws.com/$(ECR_REPOSITORY_NAME)
    tags: |
      $(IMAGE_TAG)
- task: ECRPushImage@1
  displayName: 'Push Image'
  inputs:
    awsCredentials: 'aws-fariadevops-marcio'
    regionName: $(AWS_REGION)
    sourceImageName: $(AWS_ACCOUNT_ID).dkr.ecr.$(AWS_REGION).amazonaws.com/$(ECR_REPOSITORY_NAME)
    sourceImageTag: $(IMAGE_TAG)
    repositoryName: $(ECR_REPOSITORY_NAME)
    pushTag: $(IMAGE_TAG)