# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  IMAGE_TAG: latest

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        # containerRegistry: 'your-aws-container-registry-service-connection'
        # repository: '$(AWS_ACCOUNT_ID).dkr.ecr.$(AWS_REGION).amazonaws.com/$(ECR_REPOSITORY_NAME)'
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(IMAGE_TAG)
- stage: Push
  displayName: Push image
  jobs:
  - job: Push
    displayName: Push
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Bash@3
      displayName: Push an image
      inputs:
        targetType: 'inline'
        script: |
          # Authenticate to ECR
          AWS_ECR_LOGIN=`aws ecr get-login-password --region $(AWS_REGION)`
          docker login -u AWS -p ${AWS_ECR_LOGIN} https://$(AWS_ACCOUNT_ID).dkr.ecr.$(AWS_REGION).amazonaws.com
          
          # Push Docker image to ECR
          docker tag your-image-name:$(IMAGE_TAG) $(AWS_ACCOUNT_ID).dkr.ecr.$(AWS_REGION).amazonaws.com/$(ECR_REPOSITORY_NAME):$(IMAGE_TAG)
          docker push $(AWS_ACCOUNT_ID).dkr.ecr.$(AWS_REGION).amazonaws.com/$(ECR_REPOSITORY_NAME):$(IMAGE_TAG)