variable "vpc_cidr" {}
variable "subnet_private_name" {}
variable "subnet_private_cidr" {}
variable "subnet_public_name" {}
variable "subnet_public_cidr" {}
variable "azs" {}
variable "project_name" {}
variable "cidr_block_all" {}
variable "rule_no_acl" {}
variable "ami" {}
variable "instance_type" {}
variable "db_name" {}
variable "db_master_username" {}
variable "db_subnet_group_name" {}
variable "db_engine" {}
variable "db_engine_version" {}
variable "db_instance_class" {}
